### ISSUE TITLE
[BUG] secrets not ignored in .infisicalignore on subsequent scans

### ISSUE THREAD

**Issue by cpritchett** [guibranco/github-infisical-secrets-check-action#64]
### Description

I may be misunderstanding how Infisical works due to a lack of experience with the tool, but when I place the fingerprints of the secrets that I need to be ignored in the .infisicalignore file, they are not ignored on subsequent runs of the check (which produces a different fingerprint).

### Logs

Example:
In a PR the first scan may have these results:
```
5:22PM INF scanning for exposed secrets...
5:23PM INF 1 commits scanned.
5:23PM INF scan completed in 51.6s
5:23PM WRN leaks found:15
```
sample:
```
1234567890abcdef1234567890abcdef12345678:wp-content/plugins/akismet/class.akismet-rest-api.php:generic-api-key:396
1234567890abcdef1234567890abcdef12345678:wp-content/plugins/genesis-blocks/src/blocks/block-author-profile/deprecated/2.0.0/utils/migrate.test.js:generic-api-key:16
1234567890abcdef1234567890abcdef12345678:wp-content/plugins/genesis-blocks/src/blocks/block-author-profile/deprecated/2.0.0/utils/migrate.test.js:generic-api-key:36
...
```

After updating the .infisicalignore file, subsequent updates in the PR that trigger the check again have a different fingerprint for the same files:

```
5:39PM INF scanning for exposed secrets...
5:40PM INF 1 commits scanned.
5:40PM INF scan completed in 51.6s
5:40PM WRN leaks found: 15
```
sample:
```
87654321fedcba0987654321fedcba0987654321:wp-content/plugins/akismet/class.akismet-rest-api.php:generic-api-key:396
87654321fedcba0987654321fedcba0987654321:wp-content/plugins/genesis-blocks/src/blocks/block-author-profile/deprecated/2.0.0/utils/migrate.test.js:generic-api-key:16
87654321fedcba0987654321fedcba0987654321:wp-content/plugins/genesis-blocks/src/blocks/block-author-profile/deprecated/2.0.0/utils/migrate.test.js:generic-api-key:36
...
```

**Comment by guibranco** [comment]
Hi @cpritchett, how did you run the check the second time? Were they part of the same GIT baseline?

If the commits with the secrets differ each time, you should not use the fingerprint but another method to ignore the "false positive" secret leak.

Here, you can understand better how the Infisical CLI works and ignores secrets:
- https://infisical.com/docs/cli/scanning-overview#creating-a-baseline
- https://infisical.com/docs/cli/scanning-overview#infisical-scan-ignore
- https://infisical.com/docs/cli/scanning-overview#infisicalignore

**Comment by cpritchett** [comment]
Hi @guibranco thank you for the clarification.  I believe I was using .infisicalignore how I needed to be using infisical-scan.toml and establishing the baselines.  I have some repositories that include upstream dependencies that unfortunately will always have some code being pulled in that includes "example" api keys and such, so I'll just need to exclude those files/paths.
